module.exports =
[ 'raindrops on roses'
, 'whiskers on kittens'
, 'bright copper kettles'
, 'warm woolen mittens'
, 'brown paper packages tied up with strings'
, 'cream colored ponies'
, 'crisp apple streudels'
, 'doorbells'
, 'sleigh bells'
, 'schnitzel with noodles'
, 'wild geese that fly with the moon on their wings'
, 'girls in white dresses with blue satin sashes'
, 'snowflakes that stay on my nose and eyelashes'
, 'silver white winters that melt into springs'
]
